### PR TITLE
typo - violtion

### PR DESCRIPTION
**Pull request by pwin**
changing typo in vio:ClassInheritanceViolation

### CODE REVIEW

**Comment by GavinMendelGleason** [comment]
This looks good, but the pull request should go into the dev branch so that it can be folded into a release.

**Comment by pwin** [comment]
Ok. What would you like me to do? Resubmit, it will you just sort this
simple change on the dev branch yourself?

**Comment by GavinMendelGleason** [comment]
You can resubmit or I can just fix it. Thanks a lot for finding it!

**Comment by pwin** [comment]
Gavin, it's 4 in the morning. Please can you just go ahead and fix it. That
way it's done and I can sleep soundly in that knowledge. 😁

**Comment by luke-feeney** [comment]
Heroics at 4am!

**Comment by pwin** [comment]
Indeed!

**Comment by rrooij** [comment]
It was already fixed now, so I will close this issue. Thanks for your pull request. :+1:

**Pull request closed without merging**
